INSERT INTO workers (DAILY_INCOME, NAME) VALUES (200.0, 'ANGELO');
INSERT INTO workers (DAILY_INCOME, NAME) VALUES (150.0, 'ELIAS');
INSERT INTO workers (DAILY_INCOME, NAME) VALUES (100.0, 'GUSTAVO');
